pub mod dirs;
pub mod help;
pub mod init;
pub mod mihomo_ipc;
#[cfg(target_os = "linux")]
pub mod linux;
pub mod network;
pub mod notification;
pub mod resolve;
#[cfg(target_os = "windows")]
pub mod schtasks;
pub mod server;
pub mod singleton;
pub mod tmpl;
pub mod wall_clock;
pub mod window_manager;
